FROM golang:1.16.2-alpine

ARG helm_ver=v3.5.3

RUN apk add --no-cache git curl openssl bash
RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 && chmod +x get_helm.sh && ./get_helm.sh --version ${helm_ver}

WORKDIR /app/test/
COPY test/go.mod test/go.sum .
RUN go mod download
COPY test/ .

WORKDIR /app/examples/
COPY ./examples/ .

WORKDIR /app/test/
CMD ["sh", "-c", "CGO_ENABLED=0 go test -v"]
